const mongoose = require("mongoose");

const foodSchema = new mongoose.Schema({
  id: { type: String, required: true, unique: true },
  name: { type: String, required: true },
  "nutrition-per-100g": {
    energy: { type: Number, required: false },
    protein: { type: Number, required: false },
    fat: { type: Number, required: false },
    saturatedFat: { type: Number, required: false },
    carbohydrate: { type: Number, required: false },
    sugars: { type: Number, required: false },
    dietaryFibre: { type: Number, required: false },
    sodium: { type: Number, required: false },
    potassium: { type: Number, required: false },
    transFat: { type: Number, required: false },
    polyunsaturatedFat: { type: Number, required: false },
    monounsaturatedFat: { type: Number, required: false },
    calcium: { type: Number, required: false },
    vitaminE: { type: Number, required: false },
    vitaminB3: { type: Number, required: false },
    magnesium: { type: Number, required: false },
    vitaminB1: { type: Number, required: false },
    vitaminB2: { type: Number, required: false },
    vitaminB6: { type: Number, required: false },
    vitaminB9: { type: Number, required: false },
    vitaminC: { type: Number, required: false },
    iron: { type: Number, required: false },
    phosphorus: { type: Number, required: false },
    zinc: { type: Number, required: false },
    manganese: { type: Number, required: false },
    vitaminK: { type: Number, required: false },
    vitaminA: { type: Number, required: false },
    starch: { type: Number, required: false },
    omega3FattyAcid: { type: Number, required: false },
  },
  "nutrition-per-100ml": {
    energy: { type: Number, required: false },
    protein: { type: Number, required: false },
    fat: { type: Number, required: false },
    saturatedFat: { type: Number, required: false },
    transFat: { type: Number, required: false },
    polyunsaturatedFat: { type: Number, required: false },
    monounsaturatedFat: { type: Number, required: false },
    carbohydrate: { type: Number, required: false },
    sugars: { type: Number, required: false },
    dietaryFibre: { type: Number, required: false },
    sodium: { type: Number, required: false },
    potassium: { type: Number, required: false },
    calcium: { type: Number, required: false },
    vitaminE: { type: Number, required: false },
    vitaminB3: { type: Number, required: false },
    magnesium: { type: Number, required: false },
    vitaminB1: { type: Number, required: false },
    vitaminB2: { type: Number, required: false },
    vitaminB6: { type: Number, required: false },
    vitaminB9: { type: Number, required: false },
    vitaminC: { type: Number, required: false },
    iron: { type: Number, required: false },
    phosphorus: { type: Number, required: false },
    zinc: { type: Number, required: false },
    manganese: { type: Number, required: false },
    vitaminK: { type: Number, required: false },
    vitaminA: { type: Number, required: false },
    starch: { type: Number, required: false },
    omega3FattyAcid: { type: Number, required: false },
  },
  tags: [String],
});

const Food = mongoose.model("Food", foodSchema);

module.exports = Food;
